### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by baatochan** [jonaro00/AutoTrader#5]
Hey,
Thanks for your work on this script it really helped me with the game as I'm trading 80-100 Pokemon daily with my gf since I started playing 2 months ago. Here I have some suggestion about the Linux commands.
As a lot of Linux distros doesn't allow (and all of them strongly discourage) installing python packages system-wide (without venv), I'd suggest updating the README with the commands needed to run this script inside the venv.
Additionally to run the script in the way you suggested `./trade.py` the script itself needs to have execute permission (and it's committed to the repo without it so the user needs to run `chmod +x trade.py`). However running the script this way will always use only system-wide installed packages (even when inside the vevn) so I suggest changing it to just `python trade.py` - the same way as on Windows. If you want I can edit the README myself and submit a PR.
Btw I want to update this script with a little randomness in terms of the time/click position to be 100% sure Niantic won't detect it. Would you be interested in merging that kind of change into your repo?

**Comment by jonaro00** [comment]
Thanks for the feedback!

I've opened #6, please check it out. Let me know if anything is missing.

I think the delays in communicating with the game servers together with other small inconsistencies already introduce enough randomness to not look very scripted. If Niantic actually decided to spend engineering effort on detecting this kind of timing pattern, I would laugh at them and then adjust the script. 🤣 (would rather see that effort spent on batch trading 😉)

**Comment by baatochan** [comment]
> If Niantic actually decided to spend engineering effort on detecting this kind of timing pattern
Welp, Niantic is known for banning for all weird stuff so I wouldn't be that surprised. As I don't wanna risk my account I'm probably gonna do something about that in the future, but it's not important then.

> would rather see that effort spent on batch trading
What do you mean by batch trading?

Btw recently the animation for trading Pokemon has been speed up and it's possible to lower the wait time after the confirm btn from 21s to 16s (based on my experience).

**Comment by jonaro00** [comment]
> What do you mean by batch trading?

Selecting multiple Pokemon per trade.

> lower the wait time after the confirm btn from 21s to 16s

Cool, will check it out.
